### PR TITLE
Add new check status `pending`

### PR DESCRIPTION
**Pull request by diegomarangoni**
Configuration file example:
```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        min:
          count: 1
          message: 'Someone needs to review'
    fail:
      - do: checks
        status: 'pending'
        payload:
          title: 'Awaiting approval'
          summary: 'Awaiting for an developer approval'
```

### CODE REVIEW

**Comment by iammuho** [comment]
Hey @diegomarangoni , can you push (or put to description) an example config file?

**Comment by diegomarangoni** [comment]
> Hey @diegomarangoni , can you push (or put to description) an example config file?

added to description

**Comment by iammuho** [comment]
Lgtm

**Review by iammuho — APPROVED** [review]

**Comment by iammuho** [comment]
Can you add some tests ?

**Comment by diegomarangoni** [comment]
> Can you add some tests ?

done!

**Pull request merged**
